"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.contributor_response import ContributorResponse
from ...models.error_response import ErrorResponse
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    email: str | Unset = UNSET,
    username: str | Unset = UNSET,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["email"] = email

    params["username"] = username

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/contributor",
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> ContributorResponse | ErrorResponse | None:
    if response.status_code == 200:
        response_200 = ContributorResponse.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = ErrorResponse.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = ErrorResponse.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = ErrorResponse.from_dict(response.json())

        return response_404

    if response.status_code == 500:
        response_500 = ErrorResponse.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[ContributorResponse | ErrorResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    email: str | Unset = UNSET,
    username: str | Unset = UNSET,
) -> Response[ContributorResponse | ErrorResponse]:
    """Get contributor by email or username

     Get a contributor by their email address or GitHub username

    Args:
        email (str | Unset):
        username (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ContributorResponse | ErrorResponse]
    """

    kwargs = _get_kwargs(
        email=email,
        username=username,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    email: str | Unset = UNSET,
    username: str | Unset = UNSET,
) -> ContributorResponse | ErrorResponse | None:
    """Get contributor by email or username

     Get a contributor by their email address or GitHub username

    Args:
        email (str | Unset):
        username (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ContributorResponse | ErrorResponse
    """

    return sync_detailed(
        client=client,
        email=email,
        username=username,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    email: str | Unset = UNSET,
    username: str | Unset = UNSET,
) -> Response[ContributorResponse | ErrorResponse]:
    """Get contributor by email or username

     Get a contributor by their email address or GitHub username

    Args:
        email (str | Unset):
        username (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ContributorResponse | ErrorResponse]
    """

    kwargs = _get_kwargs(
        email=email,
        username=username,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    email: str | Unset = UNSET,
    username: str | Unset = UNSET,
) -> ContributorResponse | ErrorResponse | None:
    """Get contributor by email or username

     Get a contributor by their email address or GitHub username

    Args:
        email (str | Unset):
        username (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ContributorResponse | ErrorResponse
    """

    return (
        await asyncio_detailed(
            client=client,
            email=email,
            username=username,
        )
    ).parsed
