"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

"""Contains all the data models used in inputs/outputs"""

from .activity import Activity
from .advisory_attribution import AdvisoryAttribution
from .advisory_attributions import AdvisoryAttributions
from .advisory_response import AdvisoryResponse
from .architecture_option import ArchitectureOption
from .architectures_by_package_type import ArchitecturesByPackageType
from .attribution_metadata import AttributionMetadata
from .breach_detail import BreachDetail
from .breach_info import BreachInfo
from .breached_contributor_email_detail import BreachedContributorEmailDetail
from .code_hygiene import CodeHygiene
from .commit_frequency import CommitFrequency
from .contributions import Contributions
from .contributions_repos_contributed_to_item import ContributionsReposContributedToItem
from .contributor_data import ContributorData
from .contributor_list_item import ContributorListItem
from .contributor_response import ContributorResponse
from .contributor_risk import ContributorRisk
from .contributor_risk_maintainer_geo_distribution import (
    ContributorRiskMaintainerGeoDistribution,
)
from .contributor_security import ContributorSecurity
from .contributor_security_response import ContributorSecurityResponse
from .data_source_attribution import DataSourceAttribution
from .error_response import ErrorResponse
from .identity import Identity
from .key_change import KeyChange
from .locations_item import LocationsItem
from .metadata import Metadata
from .organizations_item import OrganizationsItem
from .package_affiliation import PackageAffiliation
from .package_data import PackageData
from .package_data_dependencies_item import PackageDataDependenciesItem
from .package_data_package_details import PackageDataPackageDetails
from .package_data_repository_details import PackageDataRepositoryDetails
from .package_dependent_response import PackageDependentResponse
from .package_response import PackageResponse
from .package_search_response import PackageSearchResponse
from .popularity import Popularity
from .repository_data import RepositoryData
from .repository_health import RepositoryHealth
from .repository_health_response import RepositoryHealthResponse
from .repository_info import RepositoryInfo
from .repository_response import RepositoryResponse
from .scorecard_check import ScorecardCheck
from .scorecard_check_risk import ScorecardCheckRisk
from .scorecard_type_0 import ScorecardType0
from .security_config import SecurityConfig
from .signing_key_info import SigningKeyInfo

__all__ = (
    "Activity",
    "AdvisoryAttribution",
    "AdvisoryAttributions",
    "AdvisoryResponse",
    "ArchitectureOption",
    "ArchitecturesByPackageType",
    "AttributionMetadata",
    "BreachDetail",
    "BreachedContributorEmailDetail",
    "BreachInfo",
    "CodeHygiene",
    "CommitFrequency",
    "Contributions",
    "ContributionsReposContributedToItem",
    "ContributorData",
    "ContributorListItem",
    "ContributorResponse",
    "ContributorRisk",
    "ContributorRiskMaintainerGeoDistribution",
    "ContributorSecurity",
    "ContributorSecurityResponse",
    "DataSourceAttribution",
    "ErrorResponse",
    "Identity",
    "KeyChange",
    "LocationsItem",
    "Metadata",
    "OrganizationsItem",
    "PackageAffiliation",
    "PackageData",
    "PackageDataDependenciesItem",
    "PackageDataPackageDetails",
    "PackageDataRepositoryDetails",
    "PackageDependentResponse",
    "PackageResponse",
    "PackageSearchResponse",
    "Popularity",
    "RepositoryData",
    "RepositoryHealth",
    "RepositoryHealthResponse",
    "RepositoryInfo",
    "RepositoryResponse",
    "ScorecardCheck",
    "ScorecardCheckRisk",
    "ScorecardType0",
    "SecurityConfig",
    "SigningKeyInfo",
)
