"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

T = TypeVar("T", bound="BreachedContributorEmailDetail")


@_attrs_define
class BreachedContributorEmailDetail:
    """
    Attributes:
        email (str): Contributor email address
        breach_count (int): Total number of breaches this email appeared in
        password_exposed_count (int): Number of breaches where passwords were exposed
    """

    email: str
    breach_count: int
    password_exposed_count: int
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        email = self.email

        breach_count = self.breach_count

        password_exposed_count = self.password_exposed_count

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "email": email,
                "breach_count": breach_count,
                "password_exposed_count": password_exposed_count,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        email = d.pop("email")

        breach_count = d.pop("breach_count")

        password_exposed_count = d.pop("password_exposed_count")

        breached_contributor_email_detail = cls(
            email=email,
            breach_count=breach_count,
            password_exposed_count=password_exposed_count,
        )

        breached_contributor_email_detail.additional_properties = d
        return breached_contributor_email_detail

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
