"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

T = TypeVar("T", bound="BreachInfo")


@_attrs_define
class BreachInfo:
    """
    Attributes:
        name (str): Name of the breach
        date (str): Date the breach occurred (YYYY-MM-DD)
        is_verified (bool): Whether the breach has been verified by HIBP
        exposed_data (list[str]): Types of data exposed in the breach (e.g. Passwords, Email addresses)
        source (str): Attribution source for the breach data
    """

    name: str
    date: str
    is_verified: bool
    exposed_data: list[str]
    source: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        date = self.date

        is_verified = self.is_verified

        exposed_data = self.exposed_data

        source = self.source

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "name": name,
                "date": date,
                "is_verified": is_verified,
                "exposed_data": exposed_data,
                "source": source,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        name = d.pop("name")

        date = d.pop("date")

        is_verified = d.pop("is_verified")

        exposed_data = cast(list[str], d.pop("exposed_data"))

        source = d.pop("source")

        breach_info = cls(
            name=name,
            date=date,
            is_verified=is_verified,
            exposed_data=exposed_data,
            source=source,
        )

        breach_info.additional_properties = d
        return breach_info

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
