"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

if TYPE_CHECKING:
    from ..models.breach_info import BreachInfo


T = TypeVar("T", bound="BreachDetail")


@_attrs_define
class BreachDetail:
    """
    Attributes:
        email (str): The contributor email address
        has_breach (bool): Whether this email has appeared in any known breaches
        breach_count (int): Number of breaches this email appeared in
        breaches (list[BreachInfo]):
    """

    email: str
    has_breach: bool
    breach_count: int
    breaches: list[BreachInfo]
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        email = self.email

        has_breach = self.has_breach

        breach_count = self.breach_count

        breaches = []
        for breaches_item_data in self.breaches:
            breaches_item = breaches_item_data.to_dict()
            breaches.append(breaches_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "email": email,
                "has_breach": has_breach,
                "breach_count": breach_count,
                "breaches": breaches,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.breach_info import BreachInfo

        d = dict(src_dict)
        email = d.pop("email")

        has_breach = d.pop("has_breach")

        breach_count = d.pop("breach_count")

        breaches = []
        _breaches = d.pop("breaches")
        for breaches_item_data in _breaches:
            breaches_item = BreachInfo.from_dict(breaches_item_data)

            breaches.append(breaches_item)

        breach_detail = cls(
            email=email,
            has_breach=has_breach,
            breach_count=breach_count,
            breaches=breaches,
        )

        breach_detail.additional_properties = d
        return breach_detail

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
