"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="CodeHygiene")


@_attrs_define
class CodeHygiene:
    """
    Attributes:
        has_lockfile (bool):
        has_gitignore (bool):
        repo_size_kb (int):
        default_branch (str):
        is_fork (bool):
        topics (list[str]):
        license_spdx (None | str | Unset): SPDX license identifier. Null if no license detected.
        parent_repo (None | str | Unset): Parent repository full name (e.g., "original-org/repo"). Null if not a fork.
    """

    has_lockfile: bool
    has_gitignore: bool
    repo_size_kb: int
    default_branch: str
    is_fork: bool
    topics: list[str]
    license_spdx: None | str | Unset = UNSET
    parent_repo: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        has_lockfile = self.has_lockfile

        has_gitignore = self.has_gitignore

        repo_size_kb = self.repo_size_kb

        default_branch = self.default_branch

        is_fork = self.is_fork

        topics = self.topics

        license_spdx: None | str | Unset
        if isinstance(self.license_spdx, Unset):
            license_spdx = UNSET
        else:
            license_spdx = self.license_spdx

        parent_repo: None | str | Unset
        if isinstance(self.parent_repo, Unset):
            parent_repo = UNSET
        else:
            parent_repo = self.parent_repo

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "has_lockfile": has_lockfile,
                "has_gitignore": has_gitignore,
                "repo_size_kb": repo_size_kb,
                "default_branch": default_branch,
                "is_fork": is_fork,
                "topics": topics,
            }
        )
        if license_spdx is not UNSET:
            field_dict["license_spdx"] = license_spdx
        if parent_repo is not UNSET:
            field_dict["parent_repo"] = parent_repo

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        has_lockfile = d.pop("has_lockfile")

        has_gitignore = d.pop("has_gitignore")

        repo_size_kb = d.pop("repo_size_kb")

        default_branch = d.pop("default_branch")

        is_fork = d.pop("is_fork")

        topics = cast(list[str], d.pop("topics"))

        def _parse_license_spdx(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        license_spdx = _parse_license_spdx(d.pop("license_spdx", UNSET))

        def _parse_parent_repo(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        parent_repo = _parse_parent_repo(d.pop("parent_repo", UNSET))

        code_hygiene = cls(
            has_lockfile=has_lockfile,
            has_gitignore=has_gitignore,
            repo_size_kb=repo_size_kb,
            default_branch=default_branch,
            is_fork=is_fork,
            topics=topics,
            license_spdx=license_spdx,
            parent_repo=parent_repo,
        )

        code_hygiene.additional_properties = d
        return code_hygiene

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
