"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.advisory_attribution import AdvisoryAttribution
    from ..models.contributions import Contributions
    from ..models.identity import Identity
    from ..models.locations_item import LocationsItem
    from ..models.metadata import Metadata
    from ..models.organizations_item import OrganizationsItem


T = TypeVar("T", bound="ContributorData")


@_attrs_define
class ContributorData:
    """
    Attributes:
        summary (Contributions):
        identity (Identity):
        organizations (list[OrganizationsItem]):
        locations (list[LocationsItem]):
        security_available (bool): True if the contributor has security information in the `/contributor/security`
            endpoint
        metadata (Metadata):
        advisories (list[AdvisoryAttribution] | Unset):
    """

    summary: Contributions
    identity: Identity
    organizations: list[OrganizationsItem]
    locations: list[LocationsItem]
    security_available: bool
    metadata: Metadata
    advisories: list[AdvisoryAttribution] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        summary = self.summary.to_dict()

        identity = self.identity.to_dict()

        organizations = []
        for componentsschemas_organizations_item_data in self.organizations:
            componentsschemas_organizations_item = (
                componentsschemas_organizations_item_data.to_dict()
            )
            organizations.append(componentsschemas_organizations_item)

        locations = []
        for componentsschemas_locations_item_data in self.locations:
            componentsschemas_locations_item = (
                componentsschemas_locations_item_data.to_dict()
            )
            locations.append(componentsschemas_locations_item)

        security_available = self.security_available

        metadata = self.metadata.to_dict()

        advisories: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.advisories, Unset):
            advisories = []
            for componentsschemas_advisories_attributed_item_data in self.advisories:
                componentsschemas_advisories_attributed_item = (
                    componentsschemas_advisories_attributed_item_data.to_dict()
                )
                advisories.append(componentsschemas_advisories_attributed_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "summary": summary,
                "identity": identity,
                "organizations": organizations,
                "locations": locations,
                "security_available": security_available,
                "metadata": metadata,
            }
        )
        if advisories is not UNSET:
            field_dict["advisories"] = advisories

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.advisory_attribution import AdvisoryAttribution
        from ..models.contributions import Contributions
        from ..models.identity import Identity
        from ..models.locations_item import LocationsItem
        from ..models.metadata import Metadata
        from ..models.organizations_item import OrganizationsItem

        d = dict(src_dict)
        summary = Contributions.from_dict(d.pop("summary"))

        identity = Identity.from_dict(d.pop("identity"))

        organizations = []
        _organizations = d.pop("organizations")
        for componentsschemas_organizations_item_data in _organizations:
            componentsschemas_organizations_item = OrganizationsItem.from_dict(
                componentsschemas_organizations_item_data
            )

            organizations.append(componentsschemas_organizations_item)

        locations = []
        _locations = d.pop("locations")
        for componentsschemas_locations_item_data in _locations:
            componentsschemas_locations_item = LocationsItem.from_dict(
                componentsschemas_locations_item_data
            )

            locations.append(componentsschemas_locations_item)

        security_available = d.pop("security_available")

        metadata = Metadata.from_dict(d.pop("metadata"))

        _advisories = d.pop("advisories", UNSET)
        advisories: list[AdvisoryAttribution] | Unset = UNSET
        if _advisories is not UNSET:
            advisories = []
            for componentsschemas_advisories_attributed_item_data in _advisories:
                componentsschemas_advisories_attributed_item = (
                    AdvisoryAttribution.from_dict(
                        componentsschemas_advisories_attributed_item_data
                    )
                )

                advisories.append(componentsschemas_advisories_attributed_item)

        contributor_data = cls(
            summary=summary,
            identity=identity,
            organizations=organizations,
            locations=locations,
            security_available=security_available,
            metadata=metadata,
            advisories=advisories,
        )

        contributor_data.additional_properties = d
        return contributor_data

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
