"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

T = TypeVar("T", bound="ContributionsReposContributedToItem")


@_attrs_define
class ContributionsReposContributedToItem:
    """
    Attributes:
        url (str): Repository URL
        has_signed_commits (bool): True if contributor has at least one signed commit to this repository
        has_unsigned_commits (bool): True if contributor has at least one unsigned commit to this repository
    """

    url: str
    has_signed_commits: bool
    has_unsigned_commits: bool
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        url = self.url

        has_signed_commits = self.has_signed_commits

        has_unsigned_commits = self.has_unsigned_commits

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "url": url,
                "has_signed_commits": has_signed_commits,
                "has_unsigned_commits": has_unsigned_commits,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        url = d.pop("url")

        has_signed_commits = d.pop("has_signed_commits")

        has_unsigned_commits = d.pop("has_unsigned_commits")

        contributions_repos_contributed_to_item = cls(
            url=url,
            has_signed_commits=has_signed_commits,
            has_unsigned_commits=has_unsigned_commits,
        )

        contributions_repos_contributed_to_item.additional_properties = d
        return contributions_repos_contributed_to_item

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
