"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.breached_contributor_email_detail import (
        BreachedContributorEmailDetail,
    )
    from ..models.contributor_risk_maintainer_geo_distribution import (
        ContributorRiskMaintainerGeoDistribution,
    )


T = TypeVar("T", bound="ContributorRisk")


@_attrs_define
class ContributorRisk:
    """
    Attributes:
        total_contributors (int):
        active_contributors_12mo (int):
        bus_factor (int): Minimum number of contributors responsible for >= 80% of recent commits
        single_maintainer_risk (bool):
        maintainer_org_diversity (int): Number of distinct organizations among top contributors
        new_maintainer_flag (bool): True if the top committer has less than 6 months tenure
        signed_commit_ratio (float): Ratio of signed to total commits (0.0-1.0)
        contributors_with_breached_creds (int): Count of contributors with known breached credentials
        contributor_breach_ratio (float): Ratio of contributors with breached credentials to total contributors
            (0.0-1.0)
        unique_breach_sources (list[str]): Unique breach sources affecting repo contributors Example: ['LinkedIn',
            'Adobe', 'Canva'].
        breached_contributor_emails (list[BreachedContributorEmailDetail]): Per-contributor breach details including
            breach count and password exposure count
        maintainer_geo_distribution (ContributorRiskMaintainerGeoDistribution): Map of country name to contributor count
            (e.g., {"Finland": 3, "Germany": 2})
        most_recent_breach_date (datetime.date | None | Unset): Most recent breach date affecting any contributor. Null
            if no breaches.
    """

    total_contributors: int
    active_contributors_12mo: int
    bus_factor: int
    single_maintainer_risk: bool
    maintainer_org_diversity: int
    new_maintainer_flag: bool
    signed_commit_ratio: float
    contributors_with_breached_creds: int
    contributor_breach_ratio: float
    unique_breach_sources: list[str]
    breached_contributor_emails: list[BreachedContributorEmailDetail]
    maintainer_geo_distribution: ContributorRiskMaintainerGeoDistribution
    most_recent_breach_date: datetime.date | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        total_contributors = self.total_contributors

        active_contributors_12mo = self.active_contributors_12mo

        bus_factor = self.bus_factor

        single_maintainer_risk = self.single_maintainer_risk

        maintainer_org_diversity = self.maintainer_org_diversity

        new_maintainer_flag = self.new_maintainer_flag

        signed_commit_ratio = self.signed_commit_ratio

        contributors_with_breached_creds = self.contributors_with_breached_creds

        contributor_breach_ratio = self.contributor_breach_ratio

        unique_breach_sources = self.unique_breach_sources

        breached_contributor_emails = []
        for breached_contributor_emails_item_data in self.breached_contributor_emails:
            breached_contributor_emails_item = (
                breached_contributor_emails_item_data.to_dict()
            )
            breached_contributor_emails.append(breached_contributor_emails_item)

        maintainer_geo_distribution = self.maintainer_geo_distribution.to_dict()

        most_recent_breach_date: None | str | Unset
        if isinstance(self.most_recent_breach_date, Unset):
            most_recent_breach_date = UNSET
        elif isinstance(self.most_recent_breach_date, datetime.date):
            most_recent_breach_date = self.most_recent_breach_date.isoformat()
        else:
            most_recent_breach_date = self.most_recent_breach_date

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "total_contributors": total_contributors,
                "active_contributors_12mo": active_contributors_12mo,
                "bus_factor": bus_factor,
                "single_maintainer_risk": single_maintainer_risk,
                "maintainer_org_diversity": maintainer_org_diversity,
                "new_maintainer_flag": new_maintainer_flag,
                "signed_commit_ratio": signed_commit_ratio,
                "contributors_with_breached_creds": contributors_with_breached_creds,
                "contributor_breach_ratio": contributor_breach_ratio,
                "unique_breach_sources": unique_breach_sources,
                "breached_contributor_emails": breached_contributor_emails,
                "maintainer_geo_distribution": maintainer_geo_distribution,
            }
        )
        if most_recent_breach_date is not UNSET:
            field_dict["most_recent_breach_date"] = most_recent_breach_date

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.breached_contributor_email_detail import (
            BreachedContributorEmailDetail,
        )
        from ..models.contributor_risk_maintainer_geo_distribution import (
            ContributorRiskMaintainerGeoDistribution,
        )

        d = dict(src_dict)
        total_contributors = d.pop("total_contributors")

        active_contributors_12mo = d.pop("active_contributors_12mo")

        bus_factor = d.pop("bus_factor")

        single_maintainer_risk = d.pop("single_maintainer_risk")

        maintainer_org_diversity = d.pop("maintainer_org_diversity")

        new_maintainer_flag = d.pop("new_maintainer_flag")

        signed_commit_ratio = d.pop("signed_commit_ratio")

        contributors_with_breached_creds = d.pop("contributors_with_breached_creds")

        contributor_breach_ratio = d.pop("contributor_breach_ratio")

        unique_breach_sources = cast(list[str], d.pop("unique_breach_sources"))

        breached_contributor_emails = []
        _breached_contributor_emails = d.pop("breached_contributor_emails")
        for breached_contributor_emails_item_data in _breached_contributor_emails:
            breached_contributor_emails_item = BreachedContributorEmailDetail.from_dict(
                breached_contributor_emails_item_data
            )

            breached_contributor_emails.append(breached_contributor_emails_item)

        maintainer_geo_distribution = (
            ContributorRiskMaintainerGeoDistribution.from_dict(
                d.pop("maintainer_geo_distribution")
            )
        )

        def _parse_most_recent_breach_date(
            data: object,
        ) -> datetime.date | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                most_recent_breach_date_type_0 = isoparse(data).date()

                return most_recent_breach_date_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.date | None | Unset, data)

        most_recent_breach_date = _parse_most_recent_breach_date(
            d.pop("most_recent_breach_date", UNSET)
        )

        contributor_risk = cls(
            total_contributors=total_contributors,
            active_contributors_12mo=active_contributors_12mo,
            bus_factor=bus_factor,
            single_maintainer_risk=single_maintainer_risk,
            maintainer_org_diversity=maintainer_org_diversity,
            new_maintainer_flag=new_maintainer_flag,
            signed_commit_ratio=signed_commit_ratio,
            contributors_with_breached_creds=contributors_with_breached_creds,
            contributor_breach_ratio=contributor_breach_ratio,
            unique_breach_sources=unique_breach_sources,
            breached_contributor_emails=breached_contributor_emails,
            maintainer_geo_distribution=maintainer_geo_distribution,
            most_recent_breach_date=most_recent_breach_date,
        )

        contributor_risk.additional_properties = d
        return contributor_risk

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
