"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

T = TypeVar("T", bound="KeyChange")


@_attrs_define
class KeyChange:
    """
    Attributes:
        old_key_id (str):
        new_key_id (str):
        detected_at (datetime.datetime):
    """

    old_key_id: str
    new_key_id: str
    detected_at: datetime.datetime
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        old_key_id = self.old_key_id

        new_key_id = self.new_key_id

        detected_at = self.detected_at.isoformat()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "old_key_id": old_key_id,
                "new_key_id": new_key_id,
                "detected_at": detected_at,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        old_key_id = d.pop("old_key_id")

        new_key_id = d.pop("new_key_id")

        detected_at = isoparse(d.pop("detected_at"))

        key_change = cls(
            old_key_id=old_key_id,
            new_key_id=new_key_id,
            detected_at=detected_at,
        )

        key_change.additional_properties = d
        return key_change

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
