"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="PackageDataPackageDetails")


@_attrs_define
class PackageDataPackageDetails:
    """
    Attributes:
        homepage (str):
        license_ (str):
        summary (str):
        released_at (datetime.datetime | Unset): ISO 8601 timestamp when the package was released
    """

    homepage: str
    license_: str
    summary: str
    released_at: datetime.datetime | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        homepage = self.homepage

        license_ = self.license_

        summary = self.summary

        released_at: str | Unset = UNSET
        if not isinstance(self.released_at, Unset):
            released_at = self.released_at.isoformat()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "homepage": homepage,
                "license": license_,
                "summary": summary,
            }
        )
        if released_at is not UNSET:
            field_dict["released_at"] = released_at

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        homepage = d.pop("homepage")

        license_ = d.pop("license")

        summary = d.pop("summary")

        _released_at = d.pop("released_at", UNSET)
        released_at: datetime.datetime | Unset
        if isinstance(_released_at, Unset):
            released_at = UNSET
        else:
            released_at = isoparse(_released_at)

        package_data_package_details = cls(
            homepage=homepage,
            license_=license_,
            summary=summary,
            released_at=released_at,
        )

        package_data_package_details.additional_properties = d
        return package_data_package_details

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
