"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

if TYPE_CHECKING:
    from ..models.contributor_list_item import ContributorListItem


T = TypeVar("T", bound="PackageDataRepositoryDetails")


@_attrs_define
class PackageDataRepositoryDetails:
    """
    Attributes:
        confidence (int): A confidence rating of this attribution as a percentage (0-100)
        methods (list[str]): A list of method names that attributed this quality to the entity
        url (str):
        contributors (list[ContributorListItem]):
        has_signed_commits (bool): True if any contributor has at least one signed commit to this repository
        has_unsigned_commits (bool): True if any contributor has at least one unsigned commit to this repository
        health_available (bool): True if the repository has health information in the `/repo/health` endpoint
    """

    confidence: int
    methods: list[str]
    url: str
    contributors: list[ContributorListItem]
    has_signed_commits: bool
    has_unsigned_commits: bool
    health_available: bool
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        confidence = self.confidence

        methods = self.methods

        url = self.url

        contributors = []
        for componentsschemas_contributor_list_item_data in self.contributors:
            componentsschemas_contributor_list_item = (
                componentsschemas_contributor_list_item_data.to_dict()
            )
            contributors.append(componentsschemas_contributor_list_item)

        has_signed_commits = self.has_signed_commits

        has_unsigned_commits = self.has_unsigned_commits

        health_available = self.health_available

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "confidence": confidence,
                "methods": methods,
                "url": url,
                "contributors": contributors,
                "has_signed_commits": has_signed_commits,
                "has_unsigned_commits": has_unsigned_commits,
                "health_available": health_available,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.contributor_list_item import ContributorListItem

        d = dict(src_dict)
        confidence = d.pop("confidence")

        methods = cast(list[str], d.pop("methods"))

        url = d.pop("url")

        contributors = []
        _contributors = d.pop("contributors")
        for componentsschemas_contributor_list_item_data in _contributors:
            componentsschemas_contributor_list_item = ContributorListItem.from_dict(
                componentsschemas_contributor_list_item_data
            )

            contributors.append(componentsschemas_contributor_list_item)

        has_signed_commits = d.pop("has_signed_commits")

        has_unsigned_commits = d.pop("has_unsigned_commits")

        health_available = d.pop("health_available")

        package_data_repository_details = cls(
            confidence=confidence,
            methods=methods,
            url=url,
            contributors=contributors,
            has_signed_commits=has_signed_commits,
            has_unsigned_commits=has_unsigned_commits,
            health_available=health_available,
        )

        package_data_repository_details.additional_properties = d
        return package_data_repository_details

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
