"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

if TYPE_CHECKING:
    from ..models.repository_health import RepositoryHealth


T = TypeVar("T", bound="RepositoryHealthResponse")


@_attrs_define
class RepositoryHealthResponse:
    """
    Attributes:
        repo_url (str):
        data (RepositoryHealth):
    """

    repo_url: str
    data: RepositoryHealth
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        repo_url = self.repo_url

        data = self.data.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "repo_url": repo_url,
                "data": data,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.repository_health import RepositoryHealth

        d = dict(src_dict)
        repo_url = d.pop("repo_url")

        data = RepositoryHealth.from_dict(d.pop("data"))

        repository_health_response = cls(
            repo_url=repo_url,
            data=data,
        )

        repository_health_response.additional_properties = d
        return repository_health_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
