"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.advisory_attribution import AdvisoryAttribution
    from ..models.metadata import Metadata
    from ..models.package_affiliation import PackageAffiliation
    from ..models.repository_info import RepositoryInfo


T = TypeVar("T", bound="RepositoryData")


@_attrs_define
class RepositoryData:
    """
    Attributes:
        repository_details (RepositoryInfo):
        metadata (Metadata):
        packages (list[PackageAffiliation] | Unset):
        advisories (list[AdvisoryAttribution] | Unset):
    """

    repository_details: RepositoryInfo
    metadata: Metadata
    packages: list[PackageAffiliation] | Unset = UNSET
    advisories: list[AdvisoryAttribution] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        repository_details = self.repository_details.to_dict()

        metadata = self.metadata.to_dict()

        packages: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.packages, Unset):
            packages = []
            for packages_item_data in self.packages:
                packages_item = packages_item_data.to_dict()
                packages.append(packages_item)

        advisories: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.advisories, Unset):
            advisories = []
            for componentsschemas_advisories_attributed_item_data in self.advisories:
                componentsschemas_advisories_attributed_item = (
                    componentsschemas_advisories_attributed_item_data.to_dict()
                )
                advisories.append(componentsschemas_advisories_attributed_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "repository_details": repository_details,
                "metadata": metadata,
            }
        )
        if packages is not UNSET:
            field_dict["packages"] = packages
        if advisories is not UNSET:
            field_dict["advisories"] = advisories

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.advisory_attribution import AdvisoryAttribution
        from ..models.metadata import Metadata
        from ..models.package_affiliation import PackageAffiliation
        from ..models.repository_info import RepositoryInfo

        d = dict(src_dict)
        repository_details = RepositoryInfo.from_dict(d.pop("repository_details"))

        metadata = Metadata.from_dict(d.pop("metadata"))

        _packages = d.pop("packages", UNSET)
        packages: list[PackageAffiliation] | Unset = UNSET
        if _packages is not UNSET:
            packages = []
            for packages_item_data in _packages:
                packages_item = PackageAffiliation.from_dict(packages_item_data)

                packages.append(packages_item)

        _advisories = d.pop("advisories", UNSET)
        advisories: list[AdvisoryAttribution] | Unset = UNSET
        if _advisories is not UNSET:
            advisories = []
            for componentsschemas_advisories_attributed_item_data in _advisories:
                componentsschemas_advisories_attributed_item = (
                    AdvisoryAttribution.from_dict(
                        componentsschemas_advisories_attributed_item_data
                    )
                )

                advisories.append(componentsschemas_advisories_attributed_item)

        repository_data = cls(
            repository_details=repository_details,
            metadata=metadata,
            packages=packages,
            advisories=advisories,
        )

        repository_data.additional_properties = d
        return repository_data

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
