"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

if TYPE_CHECKING:
    from ..models.contributor_list_item import ContributorListItem


T = TypeVar("T", bound="RepositoryInfo")


@_attrs_define
class RepositoryInfo:
    """
    Attributes:
        created_at (str):
        updated_at (str):
        description (str):
        fork_count (float):
        star_count (float):
        languages (list[str]):
        contributors (list[ContributorListItem]):
        has_signed_commits (bool): True if any contributor has at least one signed commit to this repository
        has_unsigned_commits (bool): True if any contributor has at least one unsigned commit to this repository
        health_available (bool): True if the repository has health information in the `/repo/health` endpoint
    """

    created_at: str
    updated_at: str
    description: str
    fork_count: float
    star_count: float
    languages: list[str]
    contributors: list[ContributorListItem]
    has_signed_commits: bool
    has_unsigned_commits: bool
    health_available: bool
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        created_at = self.created_at

        updated_at = self.updated_at

        description = self.description

        fork_count = self.fork_count

        star_count = self.star_count

        languages = self.languages

        contributors = []
        for componentsschemas_contributor_list_item_data in self.contributors:
            componentsschemas_contributor_list_item = (
                componentsschemas_contributor_list_item_data.to_dict()
            )
            contributors.append(componentsschemas_contributor_list_item)

        has_signed_commits = self.has_signed_commits

        has_unsigned_commits = self.has_unsigned_commits

        health_available = self.health_available

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "created_at": created_at,
                "updated_at": updated_at,
                "description": description,
                "fork_count": fork_count,
                "star_count": star_count,
                "languages": languages,
                "contributors": contributors,
                "has_signed_commits": has_signed_commits,
                "has_unsigned_commits": has_unsigned_commits,
                "health_available": health_available,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.contributor_list_item import ContributorListItem

        d = dict(src_dict)
        created_at = d.pop("created_at")

        updated_at = d.pop("updated_at")

        description = d.pop("description")

        fork_count = d.pop("fork_count")

        star_count = d.pop("star_count")

        languages = cast(list[str], d.pop("languages"))

        contributors = []
        _contributors = d.pop("contributors")
        for componentsschemas_contributor_list_item_data in _contributors:
            componentsschemas_contributor_list_item = ContributorListItem.from_dict(
                componentsschemas_contributor_list_item_data
            )

            contributors.append(componentsschemas_contributor_list_item)

        has_signed_commits = d.pop("has_signed_commits")

        has_unsigned_commits = d.pop("has_unsigned_commits")

        health_available = d.pop("health_available")

        repository_info = cls(
            created_at=created_at,
            updated_at=updated_at,
            description=description,
            fork_count=fork_count,
            star_count=star_count,
            languages=languages,
            contributors=contributors,
            has_signed_commits=has_signed_commits,
            has_unsigned_commits=has_unsigned_commits,
            health_available=health_available,
        )

        repository_info.additional_properties = d
        return repository_info

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
