"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

if TYPE_CHECKING:
    from ..models.scorecard_check import ScorecardCheck


T = TypeVar("T", bound="ScorecardType0")


@_attrs_define
class ScorecardType0:
    """Null if the repository has not been scanned by OpenSSF Scorecard

    Attributes:
        aggregate_score (float): Overall Scorecard score (0.0-10.0)
        scan_date (datetime.datetime):
        version (str): Scorecard version used for the scan
        checks (list[ScorecardCheck]):
        critical_checks_failed (list[str]): Names of checks rated high/critical risk that scored below 5
    """

    aggregate_score: float
    scan_date: datetime.datetime
    version: str
    checks: list[ScorecardCheck]
    critical_checks_failed: list[str]
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        aggregate_score = self.aggregate_score

        scan_date = self.scan_date.isoformat()

        version = self.version

        checks = []
        for checks_item_data in self.checks:
            checks_item = checks_item_data.to_dict()
            checks.append(checks_item)

        critical_checks_failed = self.critical_checks_failed

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "aggregate_score": aggregate_score,
                "scan_date": scan_date,
                "version": version,
                "checks": checks,
                "critical_checks_failed": critical_checks_failed,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.scorecard_check import ScorecardCheck

        d = dict(src_dict)
        aggregate_score = d.pop("aggregate_score")

        scan_date = isoparse(d.pop("scan_date"))

        version = d.pop("version")

        checks = []
        _checks = d.pop("checks")
        for checks_item_data in _checks:
            checks_item = ScorecardCheck.from_dict(checks_item_data)

            checks.append(checks_item)

        critical_checks_failed = cast(list[str], d.pop("critical_checks_failed"))

        scorecard_type_0 = cls(
            aggregate_score=aggregate_score,
            scan_date=scan_date,
            version=version,
            checks=checks,
            critical_checks_failed=critical_checks_failed,
        )

        scorecard_type_0.additional_properties = d
        return scorecard_type_0

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
