"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.key_change import KeyChange


T = TypeVar("T", bound="SigningKeyInfo")


@_attrs_define
class SigningKeyInfo:
    """
    Attributes:
        has_signing_key (bool):
        key_change_detected (bool): True if the contributor's signing key has changed
        key_changes (list[KeyChange]):
        key_age_days (int | None | Unset): Days since the current signing key was first seen. Null if no key.
    """

    has_signing_key: bool
    key_change_detected: bool
    key_changes: list[KeyChange]
    key_age_days: int | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        has_signing_key = self.has_signing_key

        key_change_detected = self.key_change_detected

        key_changes = []
        for key_changes_item_data in self.key_changes:
            key_changes_item = key_changes_item_data.to_dict()
            key_changes.append(key_changes_item)

        key_age_days: int | None | Unset
        if isinstance(self.key_age_days, Unset):
            key_age_days = UNSET
        else:
            key_age_days = self.key_age_days

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "has_signing_key": has_signing_key,
                "key_change_detected": key_change_detected,
                "key_changes": key_changes,
            }
        )
        if key_age_days is not UNSET:
            field_dict["key_age_days"] = key_age_days

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.key_change import KeyChange

        d = dict(src_dict)
        has_signing_key = d.pop("has_signing_key")

        key_change_detected = d.pop("key_change_detected")

        key_changes = []
        _key_changes = d.pop("key_changes")
        for key_changes_item_data in _key_changes:
            key_changes_item = KeyChange.from_dict(key_changes_item_data)

            key_changes.append(key_changes_item)

        def _parse_key_age_days(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        key_age_days = _parse_key_age_days(d.pop("key_age_days", UNSET))

        signing_key_info = cls(
            has_signing_key=has_signing_key,
            key_change_detected=key_change_detected,
            key_changes=key_changes,
            key_age_days=key_age_days,
        )

        signing_key_info.additional_properties = d
        return signing_key_info

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
