"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error_response import ErrorResponse
from ...models.repository_health_response import RepositoryHealthResponse
from ...types import UNSET, Response


def _get_kwargs(
    *,
    repo_url: str,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["repo_url"] = repo_url

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/repo/health",
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> ErrorResponse | RepositoryHealthResponse | None:
    if response.status_code == 200:
        response_200 = RepositoryHealthResponse.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = ErrorResponse.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = ErrorResponse.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = ErrorResponse.from_dict(response.json())

        return response_404

    if response.status_code == 500:
        response_500 = ErrorResponse.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[ErrorResponse | RepositoryHealthResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    repo_url: str,
) -> Response[ErrorResponse | RepositoryHealthResponse]:
    """Get repository health metrics

     Get health metrics for a repository including activity, popularity, security, contributor risk, code
    hygiene, and OpenSSF Scorecard data

    Args:
        repo_url (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | RepositoryHealthResponse]
    """

    kwargs = _get_kwargs(
        repo_url=repo_url,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    repo_url: str,
) -> ErrorResponse | RepositoryHealthResponse | None:
    """Get repository health metrics

     Get health metrics for a repository including activity, popularity, security, contributor risk, code
    hygiene, and OpenSSF Scorecard data

    Args:
        repo_url (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | RepositoryHealthResponse
    """

    return sync_detailed(
        client=client,
        repo_url=repo_url,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    repo_url: str,
) -> Response[ErrorResponse | RepositoryHealthResponse]:
    """Get repository health metrics

     Get health metrics for a repository including activity, popularity, security, contributor risk, code
    hygiene, and OpenSSF Scorecard data

    Args:
        repo_url (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | RepositoryHealthResponse]
    """

    kwargs = _get_kwargs(
        repo_url=repo_url,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    repo_url: str,
) -> ErrorResponse | RepositoryHealthResponse | None:
    """Get repository health metrics

     Get health metrics for a repository including activity, popularity, security, contributor risk, code
    hygiene, and OpenSSF Scorecard data

    Args:
        repo_url (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | RepositoryHealthResponse
    """

    return (
        await asyncio_detailed(
            client=client,
            repo_url=repo_url,
        )
    ).parsed
