#!/usr/bin/env python3
"""Add code-generated header to all generated Python files."""

import sys
from pathlib import Path

HEADER = '''"""
This file was auto-generated by openapi-python-client.
Do not modify this file directly - changes will be overwritten.
"""

'''


def add_header_to_file(filepath: Path) -> bool:
    content = filepath.read_text()
    if content.startswith('"""\nThis file was auto-generated'):
        return False
    filepath.write_text(HEADER + content)
    return True


def main():
    generated_dir = Path(__file__).parent.parent / "src" / "netrise_provenance_sdk_client"
    if not generated_dir.exists():
        print(f"Generated directory not found: {generated_dir}")
        sys.exit(1)

    modified = 0
    for py_file in generated_dir.rglob("*.py"):
        if add_header_to_file(py_file):
            modified += 1

    print(f"Added code-generated header to {modified} files")


if __name__ == "__main__":
    main()
